import { Poppins } from "next/font/google";
import "../globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { Navabar } from "@/components/Navbar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // specify the weights you need
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: "Poppins, sans-serif",
              // Seed Token
              colorPrimary: "#00b96b",
              borderRadius: 20,

              // Alias Token
              colorBgContainer: "#f6ffed",
            },
          }}
        >
          <div className="flex flex-col h-screen">
            <Navabar />
            {children}
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
